// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriSpaceAPI.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NutriSpaceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528200133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriSpaceAPI.Models.Astronauta", b =>
                {
                    b.Property<int>("IdAstronauta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_astronauta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAstronauta"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("senha");

                    b.HasKey("IdAstronauta");

                    b.ToTable("TB_NS_ATRONAUTA");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.Estufa", b =>
                {
                    b.Property<int>("IdEstufa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estufa");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstufa"));

                    b.Property<int?>("AstronautaIdAstronauta")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdAstronauta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_astronauta");

                    b.Property<int>("IdPlanta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_planta");

                    b.Property<string>("NomeEstufa")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("nome_estufa");

                    b.Property<int?>("PlantaIdPlanta")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusBomba")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status_bomba");

                    b.HasKey("IdEstufa");

                    b.HasIndex("AstronautaIdAstronauta");

                    b.HasIndex("PlantaIdPlanta");

                    b.ToTable("TB_NS_ESTUFA");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.LeituraSensor", b =>
                {
                    b.Property<int>("IdLeitor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_leitor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeitor"));

                    b.Property<DateTime>("DtHrLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_hr_leitura");

                    b.Property<int>("IdEstufa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estufa");

                    b.Property<decimal>("TemperaturaLida")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("temperatura_lida");

                    b.Property<decimal>("UmidadeLida")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("umidade_lida");

                    b.HasKey("IdLeitor");

                    b.HasIndex("IdEstufa");

                    b.ToTable("TB_NS_LEITURA_SENSOR");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.Planta", b =>
                {
                    b.Property<int>("IdPlanta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_planta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanta"));

                    b.Property<string>("NomePlanta")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("nome_planta");

                    b.Property<decimal>("TempMaxIdeal")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("temp_max_ideal");

                    b.Property<decimal>("TempMinIdeal")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("temp_min_ideal");

                    b.Property<decimal>("UmiMinIdeal")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("umi_min_ideal");

                    b.HasKey("IdPlanta");

                    b.ToTable("TB_NS_PLANTA");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.Estufa", b =>
                {
                    b.HasOne("NutriSpaceAPI.Models.Astronauta", null)
                        .WithMany("Estufas")
                        .HasForeignKey("AstronautaIdAstronauta");

                    b.HasOne("NutriSpaceAPI.Models.Planta", null)
                        .WithMany("Estufas")
                        .HasForeignKey("PlantaIdPlanta");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.LeituraSensor", b =>
                {
                    b.HasOne("NutriSpaceAPI.Models.Estufa", "Estufa")
                        .WithMany("Leituras")
                        .HasForeignKey("IdEstufa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estufa");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.Astronauta", b =>
                {
                    b.Navigation("Estufas");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.Estufa", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("NutriSpaceAPI.Models.Planta", b =>
                {
                    b.Navigation("Estufas");
                });
#pragma warning restore 612, 618
        }
    }
}
